//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TacticalAgro.Analyzing {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Testing : global::System.Configuration.ApplicationSettingsBase {
        
        private static Testing defaultInstance = ((Testing)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Testing())));
        
        public static Testing Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int AttemptsMax {
            get {
                return ((int)(this["AttemptsMax"]));
            }
            set {
                this["AttemptsMax"] = value;
            }
        }
    }
}
